apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: kuberlab
  labels:
    app: kuberlab
    component: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kuberlab
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:3.2
          command: ["redis-server", "/etc/redis/redis.conf"]
          ports:
          - containerPort: 6379
          volumeMounts:
          - mountPath: /etc/redis
            name: config
      volumes:
      - name: config
        configMap:
          name: redis-config
          items:
          - key: redis.conf
            path: redis.conf